# Manually triggered workflow except when pushed to Staging

name: Production/Staging Deploy

on:
  push:
    branches:
      - staging
      - '^dev(-?[a-z]+)*$'
      - '!master'
      - '!main'

  workflow_dispatch:

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '7.4'

      - name: Build - Move files Into Project Folder
        run: |
          mkdir -p wp-content/${PROJECT_TYPE}s/${PROJECT_NAME}
          ls | grep -v wp-content | xargs mv -t wp-content/${PROJECT_TYPE}s/${PROJECT_NAME}
        env:
          PROJECT_TYPE: ${{secrets.PROJECT_TYPE}}
          PROJECT_NAME: ${{secrets.PROJECT_NAME}}

      - name: Deploy - Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo $(ssh git@git.wpengine.com info)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WPE_SSH_KEY_PRIVATE }}
          SSH_KNOWN_HOSTS: ${{ secrets.WPE_SSH_KNOWN_HOSTS }}

      - name: Deploy - Git Config - Development?
        if: contains(github.ref, 'dev')
        run: git remote add wpe git@git.wpengine.com:production/${WPE_INSTALL_DEVELOPMENT}.git
        env:
          WPE_INSTALL_DEVELOPMENT: ${{ secrets.WPE_INSTALL_DEVELOPMENT }}

      - name: Deploy - Git Config - Staging?
        if: contains(github.ref, 'staging')
        run: git remote add wpe git@git.wpengine.com:production/${WPE_INSTALL_STAGING}.git
        env:
          WPE_INSTALL_STAGING: ${{ secrets.WPE_INSTALL_STAGING }}

      - name: Deploy - Git Config - Production?
        if: contains(github.ref, 'master') || contains(github.ref, 'main')
        run: git remote add wpe git@git.wpengine.com:production/${WPE_INSTALL_PRODUCTION}.git
        env:
          WPE_INSTALL_PRODUCTION: ${{ secrets.WPE_INSTALL_PRODUCTION }}

      - name: Deploy - Git Config
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "Github Action Deployment"
           git fetch wpe
      - name: Deploy - Git Ingore
        run: |
           rm .gitignore; mv .gitignores/__production .gitignore
           echo $(ls -la ./wp-content/themes/)
      - name: Deploy - Git Push
        run: |
          git checkout -b ${GITHUB_REF##*/}-${{ github.run_id }}-${{ github.run_number }}
          git rm -r -q --cached --ignore-unmatch --force .github .gitignores composer.* gulpfile.babel.js package.json webpack.config.js yarn.lock .babelrc .editorconfig .eslintignore .eslintrc.json .stylelintrc tests
          git add .
          git status
          ls -la
          git commit -m "Deployment commit"
          git push wpe  ${GITHUB_REF##*/}-${{ github.run_id }}-${{ github.run_number }}
          git push wpe :${GITHUB_REF##*/}-${{ github.run_id }}-${{ github.run_number }}
